### ISSUE TITLE
Data Version Metadata

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/rcdb#10]
For the future:  it would be nice to have a page displaying the information in the Version_info table in the data_monitoring DB.  [note that this information may move to EventStore in the future].

Maybe it would be good to keep summary information on different run periods too, or how the runs map to run periods?

**Comment by DraTeots** [comment]
I wanted to ask, if there is an automated record about run-period somewhere. Using +10000 is pretty straight forward. But maybe there is a place with dates?

**Comment by markito3** [comment]
You can look into the mss directories for a list of files, not very 
elegant...   /mss/halld

**Comment by sdobbs** [comment]
Yeah, we've been keeping a wiki page with some run ranges and other
information, but so far on the offline side we've been scraping /mss/halld.

https://halldweb.jlab.org/wiki/index.php/Run_Periods

On the online, I think that the run period is set by the env variable
RUN_PERIOD

**Comment by DraTeots** [comment]
Could you provide more information of how to get there and get Version_info in the data_monitoring?

**Comment by DraTeots** [comment]
Run periods were added to DB in 0.9 as well as some other metadata (like schema version) I close this ticket for now as it is unclear what exactly one needs to do. Please open follow up ticket or reopen this one
