### ISSUE TITLE
RCDB web sites meta for 0.9

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/rcdb#102]
1. Merge select_value/index and select_values/search

```python
@mod.route('/')
def index():
   # ...

@mod.route('/search', methods=['GET'])
def search():
  # ...
```

I.e. 

```
rcdb/select_value/search?rr=...&q=...&cnd=...
Should become
rcdb/select_value?rr=...&q=...&cnd=...
```

**Comment by sqrd-max** [comment]
index function checks for the presence of the 'q' parameter in the URL. If it's present, it treats it as a search request; otherwise, it handles it as a regular index page request. This way, the search parameters are included in the URL only when needed.
