### ISSUE TITLE
polarimeter_converter is missing from conditions

### ISSUE THREAD

**Issue by NathanSparks** [JeffersonLab/rcdb#15]
`polarimeter_converter` is not showing up in the conditions list any more.
It was there for most runs before run 10644.

**Comment by sdobbs** [comment]
The DAQ version might need to be updated?

**Comment by DraTeots** [comment]
Updated the daq. Looks it is there. Question, would it be a good idea now to run update_epics for previous runs? (Assuming it would use start_time and set polarimeter_converter correctly?)

**Comment by sdobbs** [comment]
I actually have a slightly different code to run over previous runs,
because for that one has to access everything through MYA commands.
 update_epics mostly takes the "current" values.  I'm not sure of the best
way to merge the codes.  MYA commands are not quite foolproof...

**Comment by sdobbs** [comment]
Old runs fixed.

**Comment by sdobbs** [comment]
polarimeter_converter is showing up for new runs.  Probably can close this issue.
