### ISSUE TITLE
Adding older EPICS data workflow

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/rcdb#16]
(Continue of the discussion in #15) 
When we introduce a new condition type and a way to fill it for the next runs (parsing logs, calling EPICS), also we have a need to fill this value for the runs, that are already in DB. 

For log files, the workflow in this case is to reparse the files. For the EPICS variables, as Sean says, it is trickier. Assuming you can't just run _update_epics.py_ and give it the old run, what would be the workflow? 

Introducing one more script like _update_epics_for_existing_runs.py_?

**Comment by sdobbs** [comment]
That could work.  You should have to pass in the names of the conditions
you want to update, so you are only updating certain conditions (e.g. a new
condition variable) instead of all the EPICS variables, to avoid edge cases
with certain variables.

**Comment by DraTeots** [comment]
Lets say, then, we will pass an optional array with conditions to update. If it is null or empty, it is assumed that all conditions are to be updated. So we insert for each conditions like:

```python
    update_epics(..., cnd_to_update=[]):
    # ...
    if not cnd_to_update or 'polarimeter_converter' in cnd_to_update:
         # ... Code to update polarimeter_converter
```

**Comment by sdobbs** [comment]
Fair enough.  Will the run range be required or optional?

**Comment by DraTeots** [comment]
Do you mean 'run range' check inside ```update_epics.py```?

I would say, if in constantly changing DAQ environment the run range may fall into those "edge cases" for some conditions. 

I mean, if we stick to strategy "update_epics.py" is the only thing to use for new runs or old runs, and run-range can affect values, then it should be there.

**Comment by DraTeots** [comment]
In general update_epics just gets the run it is called upon. But you are the first person to know this =)

**Comment by sdobbs** [comment]
Well, when "update_epics_for_existing_runs.py" gets called, is it generally
passed a range of runs to work with?

**Comment by DraTeots** [comment]
@sdobbs what we do with this? How is it done in the end?

**Comment by sdobbs** [comment]
Thanks for the reminder - I don't think that most / all of the info got filled in.  But this would be just for old engineering runs - at this point, I think it's mostly just of academic interest.  So I wouldn't argue if this issue was closed.

**Comment by DraTeots** [comment]
Lets close it then for the sake of RCDB cleanup. But don't hesitate to reopen it or create a new issue if the problem ever pops up again.
