### ISSUE TITLE
Duplicate records still showing up in searches

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/rcdb#19]
Examples: 11101, 11107

**Comment by DraTeots** [comment]
I'm updating the database fill so that it is done with one transaction. hope it could help with #18 too. Because I think they are related. 2 records in one case, 2 different values (one of which is not correct) in another.

**Comment by DraTeots** [comment]
The new DAQ update scheme is shipped. Lets look if those duplicate records appear.

**Comment by DraTeots** [comment]
Still there
https://halldweb.jlab.org/rcdb/runs/info/11347
