### ISSUE TITLE
Import Sean data

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/rcdb#2]
From Sean
>Finish importing information (incl. run conditions) from the spring run into the RCDB.
We'd like to use the RCDB to drive the offline monitoring software, instead of the run conditions table that's currently being used, so this would allow us to start modifying our software to use the RCDB.

**Comment by DraTeots** [comment]
At some point I have to figure out what is missing. A help would be... helpful =)

**Comment by sdobbs** [comment]
I don't think we need to fill in information for runs before Spring 2015.  
The runs that need to be added are 2472 - 3396.  I have a script that can fill in the conditions from MYA archive.

We could add them by running over the CODA logs, or I've extracted (run_number,start_time,end_time,num_events) from my database.  Not sure which would be more accurate.

**Comment by sdobbs** [comment]
A first skim of this data has been done.  The next steps are:
1. get CODA logs off of tape and process them
2. update EPICS variables
