### ISSUE TITLE
Problem with environment.csh

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/rcdb#21]
For the offline monitoring, for some reason when I source environment.csh inside a script, I get an error telling me that I should source it, even though I already am.

For examples, see:
https://halldsvn.jlab.org/repos/trunk/scripts/monitoring/process/check_monitoring_data.csh
https://halldsvn.jlab.org/repos/trunk/scripts/monitoring/process/monitoring_env.csh

**Comment by DraTeots** [comment]
I think, the best way to solve it is to just set the environment manually. You actually only need to set PYTHONPATH, that is in general:

```
if ( ! $?PYTHONPATH ) then
    setenv PYTHONPATH "$RCDB_HOME/python"
else
    setenv PYTHONPATH "$RCDB_HOME/python":$PYTHONPATH
```

Where RCDB_HOME in case of the scripts is  
```
/work/halld2/home/gxproj1/builds/rcdb/
```

I think replacing ```source ..../environment.csh``` with ```setenv PYTHONPATH``` is the same amount of lines of code. 

The reason for that is that there is no universal way of getting the script path in CSH (all other shells have it). CCDB environment.csh strictly requires CCDB_HOME to be set. In RCDB I tried this automated way for sourcing. 

P.S. And... I understand that nobody can probably do anything about it in our computing environment, but "Csh Programming Considered Harmful"

**Comment by sdobbs** [comment]
Okay, I'll do that.  And agreed about csh ...
