### ISSUE TITLE
Several runs in RCDB show 'NONE' under polarization direction

### ISSUE THREAD

**Issue by jrstevenjlab** [JeffersonLab/rcdb#23]
see post from Elton in logbook https://logbooks.jlab.org/comment/7676#comment-7676

**Comment by sdobbs** [comment]
Looks like this is mostly due to shift crew moving the diamond around, or moving it to begin the next run before ending the current run.  Will fix this for production runs by hand.

**Comment by sdobbs** [comment]
Fixed in RCDB. There's also a problem with goniometer not properly showing that it's retracted, so I'm having to fix some other amorphous radiator runs by hand.  WIll contact Hovanes about this. But this should be fixed now.

**Comment by eltonssmith** [comment]
It looks like most entries are fixed, but there remain a few more:

Run= 11404  Date: 2016-04-15 05:27:03  triggers=   41953145 current=  128 nA  radiator= Undefined     NONE  target= FULL & Ready   <rate>= 24083 Hz  coll= 3.4mm hole

Run= 11405  Date: 2016-04-15 06:47:58  triggers=  124741923 current=  109 nA  radiator= J1A50 50um    NONE  target= FULL & Ready   <rate>= 20330 Hz  coll= 3.4mm hole

Run= 11443  Date: 2016-04-16 14:04:03  triggers=    7049828 current=   58 nA  radiator= JD70-119 20um NONE  target= FULL & Ready   <rate>=  5218 Hz  coll= 3.4mm hole

**Comment by sdobbs** [comment]
These should be fixed.  Note that run 11443 appears to be some sort of study, with half the time taken with PARA and half with PERP orientations.
