### ISSUE TITLE
Run 11554 seems to have 5 entries in RCDB

### ISSUE THREAD

**Issue by eltonssmith** [JeffersonLab/rcdb#25]
Run= 11553  Date: 2016-04-20 00:54:30  triggers=  137822845  current=   98 nA  radiator= J1A50 50um    PARA  target= FULL & Ready   <rate>= 17934 Hz  coll= 3.4mm hole

Run= 11554  Date: 2016-04-20 06:08:39  triggers=   59821129  current=  154 nA  radiator= J1A50 50um    PERP  target= FULL & Ready   <rate>= 17155 Hz  coll= 3.4mm hole
Run= 11554  Date: 2016-04-20 06:08:39  triggers=   59821129  current=  154 nA  radiator= J1A50 50um    PERP  target= FULL & Ready   <rate>= 17155 Hz  coll= 3.4mm hole
Run= 11554  Date: 2016-04-20 06:08:39  triggers=   59821129  current=  154 nA  radiator= J1A50 50um    PERP  target= FULL & Ready   <rate>= 17155 Hz  coll= 3.4mm hole
Run= 11554  Date: 2016-04-20 06:08:39  triggers=   59821129  current=  154 nA  radiator= J1A50 50um    PERP  target= FULL & Ready   <rate>= 17155 Hz  coll= 3.4mm hole

Run= 11555  Date: 2016-04-20 07:14:44  triggers=    6389322  current=   47 nA  radiator= J1A50 50um    PERP  target= FULL & Ready   <rate>=  5199 Hz  coll= 3.4mm hole

**Comment by eltonssmith** [comment]
Run 11520 nas a polarization of NONE

Run= 11520  Date: 2016-04-19 10:28:22  triggers=  161857632  current=  163 nA  radiator= J1A50 50um    NONE  target= FULL & Ready   <rate>= 21222 Hz  coll= 3.4mm hole

**Comment by DraTeots** [comment]
Captured the problem. Screenshot illustrates scripts overlapping. More important, the internal state of the scripts is captured too. So I finally fixing it. 

I remove the duplicates for now

![screenshot from 2016-04-20 14 15 59](https://cloud.githubusercontent.com/assets/4732545/14685573/f493b33c-0702-11e6-91c3-dcce27b0e0ae.png)
