### ISSUE TITLE
Correct polarization direction for runs 11368-11384

### ISSUE THREAD

**Issue by jrstevenjlab** [JeffersonLab/rcdb#29]
These runs are all labeled as PERP

For the TRD runs (11368-11380) the radiator_type=BLANK, so I'm not sure what radiator was used (if any)
https://halldweb.jlab.org/rcdb/runs/info/11369

For the next few runs (11380-11384) the polarization_direction is labeled as PERP but the radiator is amorphous so polarization_direction should be N/A
https://halldweb.jlab.org/rcdb/runs/info/11384

**Comment by sdobbs** [comment]
Not sure what the problem is with the TRD runs - the amorphous converter is parked, and HD:GONI:RADIATOR_INDEX = 2.  Maybe the goni DB is mislabeled?

Fixed the other runs.  Do we want to change the "polarization_direction" label for amorphous runs?  Consistently call is "N/A"? "AMO"?

**Comment by jrstevenjlab** [comment]
On May 20, 2016, at 1:54 PM, Sean Dobbs wrote:

> Not sure what the problem is with the TRD runs - the amorphous converter is parked, and HD:GONI:RADIATOR_INDEX = 2. Maybe the goni DB is mislabeled?

I don't know.  Since there are some non-production runs, it's probably fine to just fix them and move on.

> Fixed the other runs. Do we want to change the "polarization_direction" label for amorphous runs? Consistently call is "N/A"? "AMO"?

I'm ok with either one, as long as it's consistent.

**Comment by sdobbs** [comment]
> I don't know.  Since there are some non-production runs, it's probably fine to just fix them and move on.

I can't tell what the actual radiator was.  Since these are non-production runs, I'll leave it like this for now.

Keeping issue open until I rationalize the amorphous run labels.

**Comment by jrstevenjlab** [comment]
Also, 11455 polarization direction is PERP, but the radiator was amorphous

**Comment by NathanSparks** [comment]
The following runs in the range 10389 to 11668
have `radiator_type="3x10-4 RL"` but `polarization_direction!="N/A"`:
10563, 10634, 11095, 11295, 11433, 11434, 11438, 11455, 11635, and 11641

**Comment by NathanSparks** [comment]
It looks like run 11445's `polarization_direction` was changed to "N/A" but it should be "PERP".
`11455`'s polarization direction is still incorrect in the database.
@sdobbs Did you accidentally change the polarization direction for 11445 instead of 11455?

**Comment by sdobbs** [comment]
Mea cupla.  I've also changed all non-diamond runs to have an polarization direction of "N/A".
Let me know if you run into any more problems.
