### ISSUE TITLE
Run dependent configuration parameters?

### ISSUE THREAD

**Issue by jrstevenjlab** [JeffersonLab/rcdb#33]
Is there a simple way to find out when the standard configuration file (FCAL_BCAL_PS_m7.conf) changed over the course of the run period?  I can browse them for individual runs from the RCDB webpage, e.g. for run 11447 https://halldweb.jlab.org/rcdb/files/info/6250, but is there a way to tell at what time (or run number) the file was changed?  

I do see the label "DB id=6250 Raw" which I guess indicates an index for this config file?  Maybe thats incremented when the file changes?  If so, how can I query the file DB id vs run number?

**Comment by jrstevenjlab** [comment]
There are conditions listed on the webpage https://halldweb.jlab.org/rcdb/conditions/ for trigger_eq and trigger_type which claim to come from the config file.  I can't seem to access them via a python script, are they currently filled?

**Comment by DraTeots** [comment]
Hi Justin. Sorry for the late response, I was on vacation and surprisingly it happened to be almost entirely "internet free". 

1. How to get file versions. It can be done with python

```
from rcdb.provider import RCDBProvider
from rcdb.model import ConfigurationFile

db = RCDBProvider("mysql://rcdb@hallddb.jlab.org/rcdb")

# Get configuration file versions by name, ordered by DB ID => order by change date
files = db.session.query(ConfigurationFile)\
          .filter(ConfigurationFile.path.contains('FCAL_BCAL_PS_m7'))\
          .order_by(ConfigurationFile.id)\
          .all()

for config_file in files:
    print config_file.path, config_file.id

    # Each file has runs property - all runs where the file is used
    for run in config_file.runs:
        print "    ", run.number
```

2. trigger_eq is not filled now because miscommunication is happened with Sasha and instead of filling trigger_eq to conditions full config parser is used. One can use the parser to get any parameter from configuration file. Or, if you request, I'll add and fill any parameter of it.

**Comment by jrstevenjlab** [comment]
Hi Dmitry,  

Thanks for your feedback.  Having access to the trigger equation through RCDB would be very helpful.  I think eventually having the trigger_eq filled would be the simplest solution, but people may want access to some other variables in the config file as well.  So do you have an example of how to use the parser to retrieve the trigger equations from the config file within a python script.

Thanks,
Justin
