### ISSUE TITLE
Can't Import rcdb

### ISSUE THREAD

**Issue by jonzarling** [JeffersonLab/rcdb#39]
Tried running a python script that imported rcdb, however I see that I run into some issues just as I do "import rcdb". I'm running on a cluster with Red Hat 6.8, gcc 4.9.2, and Python 2.7.8. I successfully managed to git clone and source the environment.csh file.

Once I attempt to import I get the following message:
Traceback (most recent call last):
  File "./GetRCDB_stuff.py", line 4, in <module>
    import rcdb
  File "/gpfs/home/j/z/jzarling/Karst/gluex/gluex_build/rcdb/python/rcdb/__init__.py", line 109
    all_types_dict = {t.name: t for t in db.get_condition_types()}
                                                ^
SyntaxError: invalid syntax

I'm unfamiliar with the rcdb source code, but I imagine this should be a simple fix for an expert.

**Comment by DraTeots** [comment]
Hi!
Just can't figure out the problem. I've run rcdb successfully on RedHat 6.8. But I doesn't use GetRCDB_stuff.py - where does it comes from?

**Comment by jonzarling** [comment]
The file GetRCDB_stuff.py is the python file I was attempting to use, following the python section of the rcdb wiki. Sorry, that was probably somewhat unclear. The first lines of the python script are:

> #!/usr/bin/python
> import rcdb

The script fails at the import rcdb step, with error message above.

**Comment by NathanSparks** [comment]
I see the same SyntaxError when I run a rcdb script with python-2.6 instead of 2.7.
I think your problem is the `#!/usr/bin/python` line at the beginning of your script.
You are telling the script to use the system python which is version 2.6 on RedHat 6.
Try running `python GetRCDB_stuff.py` instead of `./GetRCDB_stuff.py`.

**Comment by jonzarling** [comment]
Ah of course it would be something dumb I did. Running
>python2.7 ./GetRCDB_stuff.py
works fine.
