### ISSUE TITLE
Build problem, conflict in bash between rcdb and rootcling

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/rcdb#41]
There appears to be a problem building sim-recon under bash after setting up RCDB. See my [blog post](https://markito3.wordpress.com/2016/08/25/build-problem-conflict-in-bash-between-rcdb-and-rootcling/) for details.

**Comment by DraTeots** [comment]
So... If I understand it right. RCDB [environment.bash](https://github.com/JeffersonLab/rcdb/blob/master/environment.bash) file has ```CPLUS_INCLUDE_PATH``` in it. It causes error somewhere related to CPLUS_INCLUDE_PATH. Is it right? 

I would ask... You said it happens only on bash. CSH version of the file - [environment.csh also sets CPLUS_INCLUDE_PATH](https://github.com/JeffersonLab/rcdb/blob/master/environment.csh#L25). What could be the difference?

**Comment by markito3** [comment]
I agree. That it works under tcsh but not bash is very confusing. It is so strange that I should probably try to repeat the experiment to make sure I was not fooling myself in some way. I recall that Alex A. was having problems building when I did not on some identical version of sim-recon. Then I tried it under bash, and reproduced the problem. Previously I has been using tcsh as I always do. But again, this should be repeated.

**Comment by sdobbs** [comment]
It looks like the same problem came up with the test builds of sim-recon,
which I was fixing yesterday..

**Comment by DraTeots** [comment]
So... Is there something should be done in RCDB?

**Comment by markito3** [comment]
I was wondering if the environment variable CPLUS_INCLUDE_PATH is necessary. Is there another way of getting the thing to link? I realize that if we did change RCDB, it might be a work-around of a ROOT problem. And that problem might disappear in the future.

There is however a real problem: doing sim-recon builds fails under bash, after the standard RCDB set-up has been done. The work-around is to unset the environment variable. It is only needed at RCDB build time anyway. But we do need to do something.

Again, this all assumes that I am reporting the problem properly. It should be reproduced under controlled circumstance, as I have mentioned before.

**Comment by DraTeots** [comment]
Is it possible to try to comment out CPLUS_INCLUDE_PATH? 


What I mean is that the ```environment.bash``` doesn't have any "magic" environment variables, without which RCDB wouldn't work.  It is just a helper script that allows one start working with RCDB right after cloning from GitHub

In terms of compiling C++ part, there are 2 things needed: 
1. Where are include files
2. Where are libraries

It could be done with ```-I``` and ```-L``` compiler flags. 

Or there are 2 lines of ```environment.bash``` doing it :

```bash
export LD_LIBRARY_PATH="$RCDB_HOME/cpp/lib":$LD_LIBRARY_PATH
export CPLUS_INCLUDE_PATH="$RCDB_HOME/cpp/include":$CPLUS_INCLUDE_PATH
```

Instead of sourcing  ```environment.bash```  helper, one could just use -I & -L compiler flags to do the job. Global compiler scripts should know where ```$RCDB_HOME``` is

**Comment by NathanSparks** [comment]
hdpm is not setting `CPLUS_INCLUDE_PATH`, and rcdb/sim-recon builds are completing just fine.
It does not appear to be needed for standard setups.

**Comment by DraTeots** [comment]
Ok) It is not clear for me:

1. Does the problem still exists or it has been fixed? 
2. Is it RCDB with CPLUS_INCLUDE_PATH, that causes the problem or RCDB is the one of many? 
3. How to resolve the issue? Remove CPLUS_INCLUDE_PATH from environment.bash?

**Comment by NathanSparks** [comment]
1. There is still this problem when CPLUS_INCLUDE_PATH is set.
2. Yes, RCDB setting CPLUS_INCLUDE_PATH is the source of this problem.
3. I would remove CPLUS_INCLUDE_PATH from both environment setup scripts to avoid similar problems in the future.

**Comment by DraTeots** [comment]
Ok! Thanks! That makes the situation clear for me. Then, my previous question/proposal is to try to comment out CPLUS_INCLUDE_PATH  in ```environment.bash``` and make everything to build without it. I believe that ```-I $RCDB_HOME/cpp/include``` should be added somewhere instead of CPLUS_INCLUDE_PATH. 

And lets remove CPLUS_INCLUDE_PATH as soon as you tell me, it works without it. At least CCDB lives somehow without it.

**Comment by markito3** [comment]
Here are some log files demonstrating the problem.
1.  [bash, CPLUS_INCLUDE_PATH set as per RCDB](https://dl.dropboxusercontent.com/u/17979289/problem.log)
2. [tcsh, CPLUS_INCLUDE_PATH set](https://dl.dropboxusercontent.com/u/17979289/coab.log)
3. [bash, CPLUS_INCLUDE_PATH unset](https://dl.dropboxusercontent.com/u/17979289/coab_bash_unset.log)
What I have not tried personally is to build RCDB with CPLUS_INCLUDE_PATH unset, which is what I suppose I should do next. :-/

**Comment by NathanSparks** [comment]
I still think that `CPLUS_INCLUDE_PATH` should be removed from all rcdb env-setup scripts.

Notice that the builtin `sim-recon` environment is now using these scripts.
https://github.com/JeffersonLab/sim-recon/pull/587/files

Richard ran into this issue last night, and we are going to keep hearing about it if `CPLUS_INCLUDE_PATH` is not removed.

**Comment by NathanSparks** [comment]
I should emphasize that I have indeed built rcdb and sim-recon with CPLUS_INCLUDE_PATH unset.
It is not needed.
