### ISSUE TITLE
tagged release, based on 0.02, with updated python components

### ISSUE THREAD

**Issue by markito3** [JeffersonLab/rcdb#68]
@sdobbs asked about a new RCDB tagged release with updated python functionality as found on the master branch. Problem is that the master branch cannot be used to build sim-recon at present. See Issue #62.

Create a new tag, [v0.02.01](https://github.com/JeffersonLab/rcdb/releases/tag/v0.02.01), to do this. The current master branch of sim-recon can be built against it (on RHEL7).

Need feedback on whether or not it does what it is supposed to do, python-wise.

**Comment by markito3** [comment]
Sean did not see what he expected. I tagged the wrong branch; got confused with an older, similarly named branch. Deleted the old tag an re-applied v0.02.01.

**Comment by sdobbs** [comment]
Looks good to me
