### ISSUE TITLE
Problem with runs 41512-41540

### ISSUE THREAD

**Issue by sdobbs** [JeffersonLab/rcdb#77]
From Naomi, I confirmed this problem too:

When I ask rcdb to print run.get_condition('cdc_gas_pressure').value   it prints it for 41510 and 41511, but then gives an error nonetype object has no attribute value.

The production runs outside the range 41512-41540 are ok.

**Comment by DraTeots** [comment]
```python
run.get_condition(...)
```

returns ```None``` if the condition is not written for the run. 
Then you have

```python
None.value   
````

which triggers the exception. 

While ```run.get_condition(...).value``` became widespread  usage of RCDB API, it is the *terriblest* way of getting constant. Not only it should be hard 'if'-ed to be safe:

```python
#safe
if run.get_condition(...) is not None and run.get_condition(...).value is not None:
    val = run.get_condition(...).value
```

But also each get_condition call spawns a database transaction which makes it slooooow. 

The recommended way is:

https://github.com/JeffersonLab/rcdb/wiki/Select-values

The example:

```python

from rcdb.provider import RCDBProvider     # import RCDB

db = RCDBProvider("mysql://rcdb@hallddb.jlab.org/rcdb")     # connect to DB

# select values (no query, but you can add '@is_production' as the second argument)
table = db.select_values(['cdc_gas_pressure'], run_min=41512, run_max=41540)

# print the result
for row in table:
    (run_number, cdc_gas_pressure) = tuple(row)
    print("{}   {}".format(run_number, cdc_gas_pressure))
```

The output (you can see those None-s)

```
41512   100.882
41513   100.863
41514   100.83
41515   100.835
41516   100.866
41517   100.841
41518   100.845
41520   100.845
41521   100.889
41524   101.026
41525   None
41528   None
41530   None
41531   None
41532   None
41533   101.425
41535   101.403
41537   101.387
41538   101.39
41539   101.375
41540   101.39
```

So it is convenient from the software point of view. It is the fastest way of getting a bunch of values with queries in python API. It handles None events

**Comment by sdobbs** [comment]
Thanks a lot for clearing that up.  I had checked the RCDB specifically for
the "None" runs and thought that I saw something on the webpage and
interactively (using the type of call you suggested)... but checking again
I indeed don't see the values.  So updated the DB as well.

---Sean
