### ISSUE TITLE
Issue with is_amorph_radiator?

### ISSUE THREAD

**Issue by jrstevenjlab** [JeffersonLab/rcdb#8]
With the query "daq_run and event_count>1000000 and @is_amorph_radiator":

https://halldweb.jlab.org/rcdb/runs/search?runFrom=0&runTo=&q=daq_run+and+event_count%3E1000000+and+%40is_amorph_radiator

there are 6 runs

10352
10368
10368
10390
10395
10416
10418

but some of these (eg. 10390) are diamond runs and some known amorphous runs (eg. 10389) do not appear in this list.  So how is is_amorph_radiator defined?  Or am I using it incorrectly?

**Comment by sdobbs** [comment]
The problem looks like it is with the definition of radiator_id, which
stores the value of HD:GONI:RADIATOR_ID.  My understanding was that
HD:GONI:RADIATOR_ID = 0 when the amorphous radiator is in.  Is this correct?

 I checked a couple runs, and these do in fact seem to be the values in
MYA.  Someone should look at the EPICS value, but I might just have to go
back and fix these entries by hand.

---Sean

**Comment by sdobbs** [comment]
This should be fixed. Changed around the definition of the search to deal with some unreliable variables.

**Comment by DraTeots** [comment]
Close the issue?

**Comment by sdobbs** [comment]
I think so.  Fixed some issues with PARA/PERP values that were recorded in some runs.

**Comment by jrstevenjlab** [comment]
Sorry I wasn't able to look at this earlier.  I just looked at one run https://halldweb.jlab.org/rcdb/runs/info/10389 and it's correctly under @is_amorph_radiator, but polarization_direction = PARA...  Looks like something similar for a couple other amorphous runs: 10435, 10456.  Can we replace these with N/A?

-Justin

**Comment by DraTeots** [comment]
Set polarization_direction to N/A for @is_amorph_radiator runs?

**Comment by sdobbs** [comment]
I will fix this.

**Comment by sdobbs** [comment]
Fixed
