### ISSUE TITLE
Missing polarimeter_converter for runs 71916-71939

### ISSUE THREAD

**Issue by jrstevenjlab** [JeffersonLab/rcdb#92]
The polarimeter_converter condition is missing for runs 71916-71939 in the Spring 2020 GlueX run period.  This condition should be set to "Be 75um" as it is for the neighboring runs.  The converter thickness is used in the flux/luminosity calculation scripts, so it's useful to get this right for the permanent record but also for data analysis.

**Comment by sdobbs** [comment]
These should be fixed now, let me know if it's not - thanks for bringing it up.
